- pom.xml
- src/deb/README.md
To clarify about the (absence of) public Debian packages for open-source users.
Per @johnfesenko's and my earlier conversation, it would be even better if we could set it up so that Maven produces the `*.deb` file only if a special goal is used (i.e., not every time you do `mvn install`).
> DPRO-3286: Add readme explaining Debian packaging

- src/main/java/org/ambraproject/rhino/content/xml/ArticleXml.java
- src/main/java/org/ambraproject/rhino/identity/Doi.java
Factored out duplication so that the Doi class formats the URL.
> DPRO-3408: Use new DOI style for "url" metadata parameter

- src/main/java/org/ambraproject/rhino/rest/controller/ArticleListCrudController.java
- src/main/java/org/ambraproject/rhino/service/ArticleListCrudService.java
- src/main/java/org/ambraproject/rhino/service/impl/ArticleListCrudServiceImpl.java
- src/main/java/org/ambraproject/rhino/view/journal/ArticleListView.java
@sbassi  since you're still new to Java let me explain what I am doing in this change.
We return JSON from Rhino. The problem here is that we were returning too much JSON data, causing the request to time out.
Until we truly need pagination, we should instead decrease the amount of JSON we return from Rhino. In this case, we do no need to include article information. Wombat does not make use of the root GET endpoint, but Lemur does. @cabanalabs is filing a ticket to look at the Lemur implementation and make sure they do not require the article metadata. If they do require the article metadata, they will have to make the request in a more specific way.
We control the JSON output from Rhino in "View" classes kept in /view/.
To fix this problem, I decided to exclude the article metadata from …
> DPRO-3491: exclude article metadata for root articleList GET

- pom.xml
- src/main/java/org/ambraproject/rhino/model/article/ArticleMetadata.java
This reverts the use of AutoValue.  We need to see if it is causing articles to fail to render in Wombat.
This keeps the subsequent addition of `ArticleMetadata.abstractText`
> Revert "Merge pull request #410 from PLOS/auto-value-experiment"

- pom.xml
- src/main/java/org/ambraproject/rhino/model/article/ArticleMetadata.java
This reintroduces the use of AutoValue.  We need to see how it is causing articles to fail to render in Wombat. I've been unable to reproduce locally.
> Remove boilerplate with ActiveObject

- pom.xml
- src/main/java/org/ambraproject/rhino/content/xml/ArticleXml.java
- src/main/java/org/ambraproject/rhino/model/article/ArticleMetadata.java
- src/main/java/org/ambraproject/rhino/service/impl/HibernatePersistenceServiceImpl.java
- src/test/java/org/ambraproject/rhino/model/article/ArticleMetadataTest.java
- src/test/java/org/ambraproject/rhino/service/IngestionTest.java
- src/test/java/org/ambraproject/rhino/service/impl/HibernatePersistenceServiceTest.java
Corrects the capitalization of the generated field name back to 'eIssn'.  This was accidentally changed to 'eissn' when I added AutoValue.
> preserve private field name eIssn, not eissn

- src/deb/control/postinst
debian packages should not clear the questions answered when installing. This
should happen when the package is purged.
@jonocodes I suspect this was to hide passwords when they were stored as strings. Otherwise I'm not sure what this was for.
> AMBR-3 debian: do not db_purge in postinst

- src/main/java/org/ambraproject/rhino/rest/controller/ConfigurationReadController.java
- src/test/java/org/ambraproject/rhino/rest/controller/ConfigurationReadControllerTest.java
This PR removes the `@RequestMapping` annotation which removes the `/config/userApi` endpoint.  The handler method still exist where we need to add back the endpoint if we find any issues in production.
I've created a **TODO** comment to remove the handler method once we're comfortable that production is working as expected.
Also, I've added unit tests to increase code coverage for `ConfigurationReadController`.
> PLT-1671 : Removed get NED authentication credentials endpoint.

- src/main/python/dbschema/migrations.json
- src/main/python/dbschema/migrations/test_migrate_ambra_1106.sql
This PR is validate [JIRA AMBR-251](https://jira.plos.org/jira/browse/AMBR-251), which fixes the Rhino salt DB migrations.
> AMBR-291 : Added test DB migration.

- pom.xml
This changes the `mvn package` step to install the built `.deb` package into an apt repo located at `/tmp/apt`.
To be used in conjunction with https://github.com/PLOS/valdo/pull/58 https://github.com/PLOS/rhino/pull/422. This simplifies the process of testing `.deb` packages in a local vagrant environment.
With this 3 PRs merged, the process to install a new, locally built rhino `.deb` package is as follows:
From the host OS:
```
~/rhino/@host$ mvn package
...
[INFO] --- apt-repo:0.2.1:apt-repo (default) @ rhino ---
[INFO] repo dir: /tmp/apt
[INFO] found deb: rhino_2.4.4+20180226223703-plos0.deb
[INFO] Attaching file: /tmp/apt/rhino_2.4.4+20180226223703-plos0.deb
[INFO] Attaching created apt-repo files: /tmp/apt/Release, /tmp/apt/Packages.gz
...
```
Then, inside the guest:
```
... …
```
> Put built .deb package into `/var/tmp/apt`, an apt repository.

- src/main/java/org/ambraproject/rhino/content/xml/AbstractArticleXml.java
- src/main/java/org/ambraproject/rhino/content/xml/AssetXml.java
- src/main/java/org/ambraproject/rhino/model/ingest/ArticlePackageBuilder.java
- src/main/java/org/ambraproject/rhino/model/ingest/AssetType.java
- src/main/java/org/ambraproject/rhino/model/ingest/FileType.java
#AMBR-606 - Added a "reviewLetter" type to Rhino ingester. This allows the creation of virtual TPR asset (<Response> blocks). Should not alter functionality is long as TPR data does not exist in the manifest.
> First pass at working Rhino for TPR

- pom.xml
Set a default value for `maven.tomcat.port`.
> Use 8082 as port when started by mvn tomcat plugin

- pom.xml
We use tomcat 7 in production, we should upgrade the maven plugin used for testing.
> Upgrade to tomcat7 maven plugin

- src/deb/tomcat7/conf/server.template.xml
Rather than use preset JMX ports, use `0`, which chooses an open port at random, to avoid conflicts.
@wryfi @heschlie I'm not sure if this will work with prometheus.
> Use random JMX ports

- src/deb/control/templates
8005 is used as the shutdown port by contentrepo. This is overwritten in salt, but we may as well change the default to not conflict with contentrepo.
> Use 8007 as default shutdown port

- src/deb/tomcat7/conf/server.template.xml
When viewing a `server.xml` file on a server using a pager, e.g. `less`, comments are hard to tell apart from active configuration. This PR removes all inactive configuration and inappropriate comments from `server.xml`.
> Delete unused comments in server.template.xml

- pom.xml
- root-index.html
It's disconcerting to visit a web service and not see anything.
Especially on recent versions of chrome where the 404 looks pretty close to the server not answering
This change add a simple landing page which links to the rhino API docs:
> Add a simple landing page

- pom.xml
Eliminates the following warning:
```
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
```
This should have no effect on the build itself, because it is using UTF-8 (see https://teamcity.plos.org/teamcity/viewLog.html?buildId=176454&buildTypeId=Diprotodon_RaroBuildJobs_RhinoTest&tab=buildLog&_focus=388#_state=336) but it will eliminate a warning message.
> Set project.build.sourceEncoding to UTF-8

- pom.xml
https://jira.plos.org/jira/browse/AMBR-930
ehcache does not seem to be used anywhere in the codebase.
> AMBR-930 Remove unused ehcache dependency

- src/main/java/org/ambraproject/rhino/service/impl/ArticleCrudServiceImpl.java
- src/main/resources/db/migration/V3__add_created_index_to_article.sql
https://jira.plos.org/jira/browse/AMBR-1015
I haven't been able to actually show this code changes fixes the problem, because I can't reproduce the problem locally. However, I can show that adding the additional sort fixes the underlying mysql pagination problem:
```
mysql> select doi from article order by created asc limit 10;
+----------------------------+
| doi                        |
+----------------------------+
| 10.1371/image.pbio.v02.i08 |
| 10.1371/image.pbio.v02.i07 |
| 10.1371/image.pbio.v02.i06 |
| 10.1371/image.pbio.v02.i05 |
| 10.1371/image.pbio.v02.i04 |
| 10.1371/image.pbio.v02.i03 |
| 10.1371/image.pbio.v02.i02 |
| 10.1371/image.pbio.v02.i01 |
| 10.1371/image.pbio.v01.i03 |
| 10.1371/image.pbio.v01.i02 |
+----------------------------+
10 rows in set (0.27 sec)
mysql> …
```
> AMBR-1015 Fix paging

- pom.xml
Solution is to stop specifying the central repo in pom.xml, there is no need.
> repo1.maven.org is no longer available via http

- src/main/java/org/ambraproject/rhino/service/taxonomy/impl/TaxonomyClassificationServiceImpl.java
- src/test/java/org/ambraproject/rhino/config/TestConfiguration.java
- src/test/java/org/ambraproject/rhino/service/taxonomy/impl/TaxonomyClassificationServiceImplTest.java
https://jira.plos.org/jira/browse/AMBR-1061
This is part of the fix for AMBR-1061. I am also going to submit tickets to fix the taxonomy classification before syndication in article admin and to clean up the old data. But this should prevent new corrections/retractions from being classified.
> AMBR-1061 Do not add taxonomy terms for corrections/retractions

- pom.xml
This uses Google's Jib plugin to publish a docker image of rhino. It's using a plos-specific tomcat base image with the correct JVM and mysq libraries installed. Build with jib:dockerBuild goal.
> add initial jib configuration

- src/main/java/org/ambraproject/rhino/identity/Doi.java
Small fix that I back-ported from the GCS branch.
Previous to this fix, recent versions of java would error with:
Tests in error:
testDoi[2: 10.1371/foo, INFO_DOI, HTTPS_DOI_RESOLVER](org.ambraproject.rhino.identity.DoiTest): java.net.MalformedURLException: Illegal character found in host: '/'
> Fix URL generation problem in recent java versions

- pom.xml
Allows connecting to more recent versions of mysql server.
> Bump mysql-connector version (used by cargo)

- pom.xml
- src/main/java/org/ambraproject/rhino/config/SwaggerConfiguration.java
In addition to being a more recent version (always good) this reduces
the number of jars included; scala is no longer necessary.
> Bump swagger springmvc to 1.0.2

- pom.xml
`mvn cargo:run` failed getting tomcat via HTTP
```
501 HTTPS Required. 
Use https://repo1.maven.org/maven2/
More information at https://links.sonatype.com/central/501-https-required
```
> ENG-325 cargo requires https mvn repo url

- src/main/java/org/ambraproject/rhino/model/Volume.java
- src/main/resources/db/migration/V6__remove_volume_sort_order_from_issue.sql
https://jira.plos.org/jira/browse/ENG-325
Dev journals is set up with the February issue of NTDs Vol. 10 sorted at the end, as you can see here:
http://journals-dev1-backend1.soma.plos.org:8006/v2/journals/PLoSNTD/volumes/10.1371%2B%2Bvolume.pntd.v10/issues
To test:
- configure to point to dev backend db
- run `mvn clean package cargo:run -DconfigDir=/etc/ambra`
- view issues sorted correctly here: http://localhost:8082/v2/journals/PLoSNTD/volumes/10.1371%2B%2Bvolume.pntd.v10/issues
> ENG-325 sort issues by doi
