- src/main/java/org/ambraproject/rhino/content/xml/ArticleXml.java
> DPRO-3378: add error handling for related articles with no doi

- pom.xml
- src/deb/control/control
@johnfesenko please take a look
> dev-DPRO-3300  initial commit

- pom.xml
@johnfesenko please take a look
> dev-DPRO-3300  removing snapshot from pom

- test/api/RequestObject/journalcc_json.py
> dev-DPRO-3360 updating integration tests as part of the dev ticket

- src/deb/tomcat7/conf/logging.properties
> DPRO-3421: increase embedded Tomcat log level to WARNING

- test/Base/Config.py
- test/api/RequestObject/journalcc_json.py
> dev-DPRO-3360 updating integration test per code changes

- test/api/RequestObject/ingestiblec_json.py
- test/api/RequestObject/zip_ingestion_json.py
@sbassi  @sjtower  please take a look
> dev-DPRO-3510 initial commit

- test/api/test_ingestiblec_json.py
> dev-DPRO-3510 removing not needed api call to rhino

- test/api/test_zip_ingestion_json.py
@sjtower  adding a flag that was dropped.
> dev-DPRO-3510 adding the do not delete elements flag

- test/api/test_zip_ingestion_json.py
> dev-DPRO-3510 updating flag to correct location

- src/main/java/org/ambraproject/rhino/model/Comment.java
- src/main/java/org/ambraproject/rhino/service/impl/CommentCrudServiceImpl.java
- src/main/java/org/ambraproject/rhino/view/comment/CommentInputView.java
- src/main/java/org/ambraproject/rhino/view/comment/CommentOutputView.java
- src/main/python/dbschema/migrations.json
- src/main/python/dbschema/migrations/migrate_ambra_1102.sql
See also: https://github.com/PLOS/plos-themes/pull/806, https://github.com/PLOS/wombat/pull/1313
> RARO-377: add name and email to anonymous comments

- test/api/resources.py
- test/data/PrePrint/aarx.2001421.xml
- test/data/PrePrint/manifest.xml
> dev-RARO-704 updating preprint test article to correct doi

- pom.xml
- src/main/java/org/ambraproject/rhino/model/article/ArticleMetadata.java
Used [goog's ValueObject](https://github.com/google/auto/blob/master/value/userguide/builders.md) to remove lots of boilerplate in this file.  The generated code is below
``` java
package org.ambraproject.rhino.model.article;
import com.google.common.collect.ImmutableList;
import java.time.LocalDate;
import java.util.List;
import javax.annotation.Generated;
import javax.annotation.Nullable;
@Generated("com.google.auto.value.processor.AutoValueProcessor")
final class AutoValue_ArticleMetadata extends ArticleMetadata {
private final String doi;
private final String title;
private final String eissn;
private final String journalName;
private final String description;
private final String rights;
private final String language;
private final String format;
private final Integer pageCount; …
```
> remove value object boilerplate

- src/test/java/org/ambraproject/rhino/content/xml/ArticleXmlTest.java
- src/test/java/org/ambraproject/rhino/service/taxonomy/impl/TaxonomyClassificationServiceImplTest.java
Eclipse is unable to infer types in certain circumstances.
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=530576
Be more explicit about types to work around this issue.
> Work around compiler bug in Eclipse

- .gitignore
- pom.xml
- src/main/java/org/ambraproject/rhino/service/impl/IngestionService.java
- src/main/java/org/ambraproject/rhino/util/Archive.java
- src/test/java/org/ambraproject/rhino/AbstractRhinoTest.java
- src/test/java/org/ambraproject/rhino/RhinoTestHelper.java
- src/test/java/org/ambraproject/rhino/config/TestConfiguration.java
- src/test/java/org/ambraproject/rhino/content/xml/ArticleXmlTest.java
- src/test/java/org/ambraproject/rhino/service/impl/IngestionServiceTest.java
- src/test/java/org/ambraproject/rhino/service/taxonomy/impl/TaxonomyClassificationServiceImplTest.java
- src/test/resources/org/ambraproject/rhino/service/impl/duplicate_assets_manifest.xml
- src/test/resources/org/ambraproject/rhino/service/impl/dupp.0000001.xml
- src/test/resources/org/ambraproject/rhino/service/impl/empty_manifest.xml
- src/test/resources/org/ambraproject/rhino/service/impl/manifest.dtd
- src/test/resources/org/ambraproject/rhino/service/impl/manifest.xml
- src/test/resources/rhino-test.yaml
This PR adds test cases to increase the code coverage for `org.ambraproject.rhino.service.impl.IngestionService`.
I modified portions of `org.ambraproject.rhino.service.impl.IngestionService` to ease the addition of the test cases.
> AMBR-121 : Increased code coverage for Rhino IngestionService

- src/test/java/org/ambraproject/rhino/AbstractRhinoTest.java
- src/test/java/org/ambraproject/rhino/service/impl/HibernatePersistenceServiceTest.java
- src/test/java/org/ambraproject/rhino/service/impl/IngestionServiceTest.java
This PR also adds unit tests for ContentRepoPersistenceServiceImpl.
> AMBR-125 : Added unit tests for service HibernatePersistenceServiceImpl.

- src/main/java/org/ambraproject/rhino/model/ingest/ArticleFileInput.java
- src/main/java/org/ambraproject/rhino/model/ingest/ArticleItemInput.java
- src/test/java/org/ambraproject/rhino/AbstractRhinoTest.java
- src/test/java/org/ambraproject/rhino/service/impl/ContentRepoPersistenceServiceTest.java
- src/test/java/org/ambraproject/rhino/service/impl/HibernatePersistenceServiceTest.java
This PR increases the test coverage for [ContentRepoPersistenceServiceImpl](https://github.com/PLOS/rhino/blob/master/src/main/java/org/ambraproject/rhino/service/impl/ContentRepoPersistenceServiceImpl.java).
> AMBR-130 : Increased code coverage for ContentRepoPersistenceServiceImpl.

- src/main/java/org/ambraproject/rhino/rest/controller/ConfigurationReadController.java
- src/test/java/org/ambraproject/rhino/rest/ConfigurationReadControllerTest.java
- src/test/java/org/ambraproject/rhino/rest/controller/ConfigurationReadControllerTest.java
This PR removes the security vulnerability that exposes the NED user name/password.
> AMBR-181 : Removed API endpoint to get NED user credentials.

- src/deb/tomcat7/conf/server.template.xml
https://jira.plos.org/jira/browse/AMBR-516
> AMBR-516 increased max threads to 1000 and minthreads to 50

- pom.xml
For local development, make `mvn install` put a `.deb` package into `/var/tmp/apt`.
> Install rhino in /var/tmp/apt

- pom.xml
https://jira.plos.org/jira/browse/AMBR-199
> AMBR-199 Upgrade commons-fileupload dependency to 1.3.3

- pom.xml
https://jira.plos.org/jira/browse/AMBR-800
Address a security issue in camel.
To test, run locally with `mvn package cargo:run`. I'm not sure what else we should test here, because I don't know how rhino triggers camel jobs.
> AMBR-800 Upgrade camel to 2.13.4

- pom.xml
https://jira.plos.org/jira/browse/AMBR-931
> AMBR-931 Remove unused aspectj dependency

- pom.xml
Updating rhino version to 2.5.3
> Updating rhino version to 2.5.3

- pom.xml
Updating develop branch to 2.5.4-SNAPSHOT
> Updating develop branch to 2.5.4-SNAPSHOT

- src/main/java/org/ambraproject/rhino/rest/controller/AssetFileCrudController.java
https://jira.plos.org/jira/browse/AMBR-941
> Remove reproxy related code

- test/api/RequestObject/articlecc.py
- test/api/test_articlecc.py
Updating integration test per changes in AMBR-1020
https://teamcity.plos.org/teamcity/viewType.html?buildTypeId=IntegrationTests_RhinoDev&branch_Rhino_Integration_Tests=AMBR-1020-QA&tab=buildTypeStatusDiv
> AMBR-1020-QA updates integration test per removal of rhino endpoints

- src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
https://jira.plos.org/jira/browse/AMBR-700
> AMBR-700 Unset baselineOnMigrate

- pom.xml
- src/main/java/com/google/gson/typeadapters/UtcDateTypeAdapter.java
- src/main/java/org/ambraproject/rhino/rest/controller/RestController.java
- src/main/java/org/ambraproject/rhino/util/JsonAdapterUtil.java
- src/test/java/com/google/gson/typeadapters/UtcDateTypeAdapterTest.java
https://jira.plos.org/jira/browse/AMBR-882
Replace functionality with:
- Use Google provided UTC GSON (de)serializer (from https://github.com/google/gson/blob/master/extras/src/main/java/com/google/gson/typeadapters/UtcDateTypeAdapter.java)
- Use apache httpclient provided date parsing
> AMBR-882 Remove rhombat dependency

- pom.xml
- src/main/java/org/ambraproject/rhino/config/HibernateLoggingInterceptor.java
- src/main/java/org/ambraproject/rhino/config/RhinoConfiguration.java
- src/main/java/org/ambraproject/rhino/config/RuntimeConfiguration.java
- src/main/java/org/ambraproject/rhino/config/YamlConfiguration.java
This reverts commit eeeffaae261b13225d310d904336afd3d3e23116, reversing
changes made to 3fe81804bcaee5535fd3729894deee0bb166abb6.
@gt-plos requested that we roll this change back until we have a plan to backfill from prod to stage.
> Revert "Merge pull request #495 from PLOS/AMBR-1056"

- .gitignore
- test/api/RequestObject/ingestion.py
- test/api/test_articlecc.py
- test/api/test_articlelistcc.py
- test/api/test_ingestiblec.py
Jira ticket: https://jira.plos.org/jira/browse/AMBR-1082
This PR:
- removed code related to syndication db
- fixed tear-down method in test_articlecc.py
- refactored test_articlelistcc.py: renamed test_cleanup to lists_cleanup as it's not a test method, added pytest fixture
- some cosmetic code changes
> AMBR-1082 update tests after dropping syndication table from ambra db

- pom.xml
- src/main/java/org/ambraproject/rhino/view/article/author/AuthorView.java
- src/test/java/org/ambraproject/rhino/view/article/author/AuthorViewTest.java
Merge #509 first.
Apparently an author can have no given names. This fixes that.
> Ambr 1069 followup
